# Generated by Django 5.2.5 on 2025-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "Dishes"},
        ),
        migrations.AddField(
            model_name="cook",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("avatars/avatar_1.png", "Avatar_1"),
                    ("avatars/avatar_1.png", "Avatar_2"),
                ],
                default="avatars/avatar_1.png",
                max_length=100,
            ),
        ),
    ]
